server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # O segredo está aqui: o uso de variáveis impede o Nginx de crashar na inicialização
    location ~ ^/clickup-api/(.*)$ {
        resolver 8.8.8.8 valid=30s;
        proxy_ssl_server_name on;
        proxy_set_header Authorization "pk_90848927_3RNB3KVYA0ZBY9YILUOJAH7RUKD61437";
        proxy_set_header Content-Type "application/json";
        proxy_pass https://api.clickup.com/api/v2/$1$is_args$args;
    }
}